### ISSUE TITLE
All RF URLs are blank

### ISSUE THREAD

**Issue by akshithaaravi** [rainforestapp/tester-chrome-extension#112]
Since this morning, the jobs I am getting does not display anything. I get the URL in a new tab and instead of oops or a job loading, Its blank, its just blank. Please help me. Thanks in advance.

**Comment by erdeminofff** [comment]
Disable your adblock or another page optimization extensions. If its doesn't work go to C:\Users\"Your User Name"\AppData\Local\Google\Chrome and rename "User Data" to any name. Its like a clean installation without losing data. Try to open links with this way and if you want to go back just change folder name to "User Data" again.

**Comment by qpPykT** [comment]
I have an error in each new tab with the task.

"ERROR: Something went wrong on our server, sorry about this. Please reload and try again."

**Comment by akshithaaravi** [comment]
@erdeminofff , What user name should I replace it with? Thanks for your help

**Comment by Deepak0988** [comment]
Since Morning get Oops Something went wrong continuously ..... Something happening at Rainforest

**Comment by erdeminofff** [comment]
@akshithaaravi https://www.youtube.com/watch?v=YlnmPhBZ728 this video ll help you

**Comment by hunt40** [comment]
i am fed up all this oops thing everyday since beginning,if 20 hit windows open 19 is oops.

**Comment by pscohn** [comment]
@akshithaaravi is this still happening? Can you open the dev console and show a screenshot of any errors if so?

**Comment by akshithaaravi** [comment]
@pscohn , No, not any more, it just happened for an hour or so , I don't even remember what I did? when I restarted, it was back to normal.

**Comment by akshithaaravi** [comment]
@pscohn , Again today I have been getting blanks screens, here is screen shot of the console. Please check and resolve the issue. Thanks!
https://www.dropbox.com/s/mimzeq9tqsuywq8/Screenshot%202016-03-25%2007.43.39.png?dl=0

**Comment by akshithaaravi** [comment]
@pscohn , I just uninstalled and installed the chrome, its resolved now, I am getting oops.

**Comment by AmaiaKao** [comment]
i have this issue for months, sent ticket to RF but still have the issue, usually after few restart and reset router, the link will go back to oops, but for few days now, it's all blank, yes I do get links straight from the plugin but could not work on it since it's all white page. I have ticket for this with screenshots (with console showing errors) I do not have adblocker, no other plugins/extension enabled, even reformatted laptop because of this. Uninstalled/reinstall chrome for several times, cleared cookies, no use. I tried checking the link on other browser but same error, blank. So for 3-4 days 0 hits for me when normally I do 10-15. I hope we can resolve this without getting blank again and again. This is only happening with tester.rainforestqa.com, all other links are fine, portal.rainforestqa.com I can open with no problem at all.

@akshithaaravi I bet it will be back to blank sooner or later. I've been dealing with this issue for months.

Thanks!

**Comment by akshithaaravi** [comment]
@AmaiaKao , I agree with you completely, everytime I start my computer and open the browser, dreading that RF pages may go blank....couple of other users also have complained this on the other forums, their situation has not resolved yet. Hopefully RF gives some attention to this and find out what is going on........Its definitely not our hardware or software issue, because when it is working fine and all of a sudden for no reason this occurs......and the console shows that it is a server 403 error......I think someone is stealing hits in between the server and the user.

**Comment by jbarber** [comment]
If any of you get a blank page, please open the console and visit one of the URLs that are returning 403 and tell us what the message is.

I suspect it will be a message from a services we use asking you to pass a CAPTCHA.

**Comment by akshithaaravi** [comment]
@jbarber , 

I don't have the error now, but I have got the screen shot of the Dev console when I was getting blank pages https://www.dropbox.com/s/mimzeq9tqsuywq8/Screenshot%202016-03-25%2007.43.39.png?dl=0

And I think one of the reasons for this blank screen is because of this message in the terminal, which happens sometime, not sure if its for that particular Hit. Please check the below image too.
https://www.dropbox.com/s/9tklfvt59uq49eb/Screenshot%202016-04-01%2012.53.37.png?dl=0
Once this hit is completed and when the next hit is allotted, its only blank screen, this is what I have experienced. Today when it happened, after I completed the hit, I shut the computer down and I restarted it. So I did not face any issues of blank screen.

Thank you!

**Comment by jbarber** [comment]
@akshithaaravi I don't believe the problem is because of any of your previous HITs. Did you visit one of the URLs that was reporting a 403?

**Comment by AmaiaKao** [comment]
I think the issue is about captcha stuff. I tried to open my link on my brother's home (different ISP) and it works fine there. I have dynamic IP so my friend told me to check "project honeypot" site to check the data my IP was having, so I found there that my IP has issues with email spamming etc. The thing is maybe my IP is blocklisted somewhere because of spamming issues and my brother's IP is not. I always get captcha every 5 minutes or so. I discussed about this in email and RF Support assisted me well. Kristen asked for my IP and gave me a temporary fix. Now I can do hits after a week of 0 hits. Thanks RF.

**Comment by AmaiaKao** [comment]
@jbarber  
HI. it's been a while since I get a blank page because RF Support staff gave me a temporary link to fix this (application.js link). So now I got a blank link, I opened the console to get the link error and here it is.
https://static.rnfrst.com/8dde8d506e542526c16626b9c8672578d1ef01d2/application.css

My blank page was fine and back to normal after this post, since I pasted the link given by RF Support Staff. Thanks Kristen :)

**Comment by pscohn** [comment]
This exact link @AmaiaKao posted changes as we release new code, so if it does not work, you can find the updated link by right clicking/view source of the page, and open the application.js/css. However, @jbarber released a fix for the problem, so it shouldn't be happening as much.
