### ISSUE TITLE
change of contributor id

### ISSUE THREAD

**Issue by rous86** [rainforestapp/tester-chrome-extension#285]
![4](https://cloud.githubusercontent.com/assets/20247825/16532344/1ce4273a-3fda-11e6-86cc-23892ed8166e.png)
hello, i have an issue with my contributor id, i signed up with rainforest more than a year ago with a neobux account that i stopped using a while ago.. the problem is that i use a clixsense account when using my crowdflower and rainforest tasks, but the rainforest has the id of payment of the neobux account that is deactivated since long time ago... what i ask is to change my contributor id from 11024474 that is now (neobux deactivated account) to 13521049 (active clixsense account)...with crowdflower i have no problem, but rainforest i have that issue, and i want to do rainforest tasks but since getting paid to an inactive account it is pointless as you understand, i hope you can change my contributor id thank you

**Comment by samballode6** [comment]
This is a really hard problem.
Very hard to change your id on RF.
I suggest you to find and do a new jobs id in CrowdFlower task for RF in your new id at Clixsense, for get and claim a new profile page.
But you can also tries send a ticket to tester@rainforestqa.com
I wish you success for that...

**Comment by rous86** [comment]
but i already sent them message but they do not reply about it, not even tell me "hey forget it no chance", or to give me instructions to do this or that...

how can i do that? even if i make a new crowdflower account the rainforest account will still be the same, and for some reason i cannot delete the rainforest account and make a new

Have u had the same issue also?

**Comment by SliderKPP** [comment]
I have the same problem, my rainforest account have my old neobux worker id, but that account no longer exist, I opened a ticket too and they still don't respond me. I tried to make another account but when I need to claim it, is the same account with my neobux worker id, and I can't delete rainforest accout too...soo yes it's annoying.

**Comment by nerdatwork** [comment]
@rous86 Rainforest support will respond to your ticket in time but please know Rainforest as of now does not change worker ids.

**Comment by SliderKPP** [comment]
@nerdatwork But how I can close this account  so I can make another one?? If I will try to make another account when I need to claim the account will be the same with this one...it's like they merge the account

**Comment by nerdatwork** [comment]
@SliderKPP You cant close your account. Rainforest support will look into your issue and provide you with a solution. The support desk is filled with support tickets but you will get a solution either way, till then keep the faith :+1:

**Comment by rous86** [comment]
so guys in order to rephrase the question, has anyone sent a support ticket and rainforest actually changed his worker id or not? and if yes, after how long since the support ticket they replied

@SliderKPP i sent my support ticket 3 days ago, how long ago did u sent it?

@nerdatwork if rainforest does not change ids, i assume at least they have to reply the support ticket and say not to do any rainforest task for users like me or @SliderKPP that have such an issue

**Comment by SliderKPP** [comment]
@rous86 I sent the ticket 3 days ago too, eh anyway, we are not the only one who have this problem, I will just wait for them to answer me. They have some more important things to do now, so I'm not in a rush. :)

**Comment by samballode6** [comment]
Hello friend,
You must do new CrowdFlower task first, to change your new contributor id.
After system has change your contributor id automatically with task you have done in new CrowdFlower task, after that you can do your first RF job.
Must try like that...

**Comment by rous86** [comment]
@samballode6 you mean to logout from my crowdflower id, signup with a new one? but the RF task require level 1 badge i think

**Comment by samballode6** [comment]
I had this problem before, but now that problem is solved.
That's the way until I succeed.

**Comment by rous86** [comment]
i tried doing what u said @samballode6 no luck still the same

**Comment by SliderKPP** [comment]
Rous86 don't make more than one crowdflower account, it's not allowed, you can be banned permanently.

**Comment by samballode6** [comment]
Yes, logout Crowdflower first, wait level 0 task appear, while task level 0 appear, click task from Clixsense, but on Crowdflower sign in, you must sign in with your old id, that will change your id 13521049 synchronize with CrowdFlower id

**Comment by samballode6** [comment]
You must tell CrowdFlower first, about you changed your id, explaint to them, what your problem, they are human too...
They can understand that...

**Comment by samballode6** [comment]
In my case, they answer like this :



Hi samballode6,

Thanks for replying.

We understand that your Contributor ID 31722590 from NeoBux is no longer active. We also understand that your Contributor ID 38173505 from NeoBux is your active ID and that you have selected it as Preferred. You will not be banned for having 2 IDs from the same website because your first one is not active.

To respond to this ticket, click Reply, type REOPEN TICKET in the message area, type your message and click Send.

Sincerely,

The Community Support Team

**Comment by samballode6** [comment]
Maybe my explaination can help you...
I wish you success for that...

**Comment by rous86** [comment]
ok guys i sent ticket, the crowdflower says send ticket to rainforest, rainforest does not reply at all...the thing @samballode6 said about signout and log with new id, doesnt work either, so if anyone expects something from it, just do not expect anything, they do not change it, it is a complete waste of time, just do the other crowdflower tasks, rainforest simply is not worthy of your time if u have different id problem like me

**Comment by nerdatwork** [comment]
@rous86 You need to calm down a bit. Its still Sunday at Rainforest and Monday is 4th of July, which is a national holiday. Have some patience and stop with the negativity. I understand your frustration.

**Comment by samballode6** [comment]
I don't understand, why you don't succeed yet.
All I do is change my not active id from Neobux and make new id on Neobux too.
I don't know, maybe you make your new id on Clixsense that make different from my ways...
Like you see on my ticket at CrowdFlower...
But one thing for your remember, I have been succeed with the same problem with you.
And I just want to help and try to give explanation for same problem.
![id 2](https://cloud.githubusercontent.com/assets/19857030/16562313/cfb60704-4226-11e6-94a3-5b8498c266e7.png)
![id 1](https://cloud.githubusercontent.com/assets/19857030/16562361/e0596f38-4226-11e6-8a31-5c7b961ff7fe.png)

**Comment by rous86** [comment]
i believe u @samballode6 that u succeeded with that but i do not know maybe as u say its because of difference between neobux and clixsense, i did what u said but from crowdflower they said it cannot change, thank u for ur time guys, ill just dont do RF if they change it in future let it be

**Comment by pscohn** [comment]
We have a high volume in tickets so it may take some time to respond to tickets individually. However we do not change IDs or close accounts. Each CrowdFlower channel will have a different Rainforest profile. If you wish to use a different CrowdFlower channel, you can log into that channel and do the starter job for Rainforest. If you already have a Rainforest profile for that channel, you will be able to log in and install the Chrome extension to start doing work.
